### ISSUE TITLE
Consider adding filtering to Set e.g. to set a subset of doors so that isLocked=true

### ISSUE THREAD

**Issue by drkevg** [w3c/automotive#136]

**Comment by rstreif** [comment]
It's probably "wildcarding" rather than "filtering". This example from the specification:

client -> {
		"action": "set",
		"path": "Signal.Cabin.Door",
		"value":{ [ {"Row1.Right.IsLocked" : true },
		            {"Row1.Left.IsLocked" : true },
			    {"Row2.Right.IsLocked" : true },
			    {"Row2.Left.IsLocked" : true } ] },
                "requestId": "5689"
		}

means that a developer would have to know how many rows and doors there are and explicitly ask for every single one to be locked. A better way would be allowing wildcards in the path:

client -> {
		"action": "set",
		"path": "Signal.Cabin.Door.*.*",
		"value":{ [ {"IsLocked" : true } ] },
                "requestId": "5689"
		}

AR: @drkevg please clarify if this is what you meant.

**Comment by drkevg** [comment]
Suggestion withdrawn. Requires wider consideration so will discuss and may re-raise if thought to be an improvement.
