### ISSUE TITLE
Change "getVSS" to "discover"

### ISSUE THREAD

**Issue by acrofts84** [w3c/automotive#210]
In order to further abstract the data model from the access methods, we should rename the "getVSS" method/action to the "discover" method/action.
- This is familiar parlance within the IoT and will be more familiar to an implementer.
- This ensures that the spec can still be logically applied to new data models, including but not limited to the VSS.

**Comment by aShinjiroUrata** [comment]
Hi @acrofts84 san

I think abstraction of 'getVSS' is good idea.

By the way, although I am not very familiar with IoT specs, this word "discover" is appropriate for this use case?
In w3c wot, "Discovery AP" is to discover IoT "things" which is like discovering devices.
http://w3c.github.io/wot/architecture/wot-architecture.html

If the word "discover" is natural in this use case, I'm OK to change.

**Comment by PeterWinzell** [comment]
I agree "discover" is better

**Comment by drkevg** [comment]
Although we like 'discover', Adam and I think Urata-san raises a good point and that using 'discover' could be confusing if we use it to discover metadata and e.g WoT use it to discover services. Would it be ok if we replaced getVSS with getMetadata instead (we also considered getSchema, but the method call returns an object with metadata rather than a schema definition, so getMetadata seems clearest)

**Comment by peterMelco** [comment]
Ok, I then change my mind :) getMetaData is more clear, so I am fine with that.

**Comment by acrofts84** [comment]
I also agree with getMetadata

**Comment by aShinjiroUrata** [comment]
Excuse me for late reply.
I'm OK with the word 'getMetadata'.

I looked more at OIC Core spec and looks, word 'discover' is used not only for 'Endpoint discovery',
  used for 'Resouce discovery' as well.
https://openconnectivity.org/developer/specifications

So, I thought something like 'discoverResouce' could be another candidate
 but it is not something like commonly used word.

So, in our case, I suppose 'getMetadata' matches well.

**Comment by rstreif** [comment]
I agree that just 'discover' is too generic and somewhat overloaded. @acrofts84, looking at OIC is a good idea because of the interaction with them and making things consistent even across different applications makes a lot of sense. 'discoverResource' has my vote but I am ok with 'getMetadata' although it's a little too generic for my taste. :)

**Comment by peterMelco** [comment]
So I will close this one since this is now changed in the spec to getMetaData
