### ISSUE TITLE
Test case for subscriptionNotificationError

### ISSUE THREAD

**Issue by wonsuk73** [w3c/automotive#247]
VISS has [subscriptionNotificationError](https://w3c.github.io/automotive/vehicle_data/vehicle_information_service.html#dfn-subscriptionNotificationError) message format in the spec below. Don't we need to have test case for this? @aShinjiroUrata what do you think?

>{
>    "$schema": "http://json-schema.org/draft-04/schema#",
>    "title": "Subscription Notification Error",
>    "description": "Error message sent by the server when there is an error with an existing subscription",
>    "type": "object",
>    "required": ["action", "subscriptionId", "error", "timestamp"],
>    "properties": {
>        "action": {
>            "enum": [ "subscription" ],
>            "description": "The identifier for the subscription notification",
>        },
>        "subscriptionId": {
>            "$ref": "#/definitions/subscriptionId"
>        },
>        "error": {
>            "$ref": "#/definitions/error"
>        },
>        "timestamp": {
>            "$ref": "#/definitions/timestamp"
>        }
>    }
>}

**Comment by aShinjiroUrata** [comment]
Hi @wonsuk73 

Actually, test 0230 in test assertion document is test for 'subscriptioNotificationError'.
(Please look at #124 's attached excel document)

However, I could not come up with a request to send to VISServer which can cause 'subscriptionNotificationError'.
So, eventually I did not write test 0230.
If you have good idea, please let me know.

I think, writing test codes those can thoroughly cover everything in spec is basically difficult.

**Comment by wonsuk73** [comment]
@aShinjiroUrata Got it. About how to make a test case for subscriptionNotificationError, I don't know either. I will also think about that :-)

**Comment by aShinjiroUrata** [comment]
> I don't know either. I will also think about that :-)

Thanks!
However, I think this might be difficult to write as automated test.

- If 'subscribe' is bad, just end up with 'subscribeError' and can not go to next step.
- So I suppose, to cause 'subscriptionNotificationError', after 'subscribe' succeed, some trouble should happen. 
- However client can not cause such trouble because what client can do is just send 'subscribe' request and send 'unsubscribe' request.
- Also, another difficulty is, this test code should be something that can certainly cause 'subscriptionNotificationError' for every VISServer implementation.

**Comment by tguild** [comment]
we are closing outdated issues, please reopen or create a new one if still relevant
