### ISSUE TITLE
Charter review

### ISSUE THREAD

**Issue by tguild** [w3c/automotive#349]
Link to be provided shortly

**Comment by tguild** [comment]
https://w3c.github.io/automotive/planning/charter-2020.html

**Comment by samuelweiler** [comment]
Opened separate issues in this repo. Your attention is drawn to https://github.com/w3c/automotive/issues/357 #358 and #359.

I wonder if the latter two would be better tackled with a comprehensive architectural document(s) rather than in individual specs. And I suspect the WG should do that broader architectural work before digging into the data specs. I think we need to resolve these questions before rechartering the WG.
